export declare const getLanguage: () => "english" | "spanish";
export declare const getTexts: () => {
    intervalsLengthQuestion: string;
    shortPauseQuestion: string;
    howManyIntervals: string;
    longPauseQuestion: string;
    onLongPause: string;
    onShortPause: string;
    onInterval: string;
    completedIntervals: string;
    paused: string;
    minute: string;
    min: string;
    second: string;
    sec: string;
} | {
    intervalsLengthQuestion: string;
    shortPauseQuestion: string;
    howManyIntervals: string;
    longPauseQuestion: string;
    onLongPause: string;
    onShortPause: string;
    onInterval: string;
    completedIntervals: string;
    paused: string;
    minute: string;
    min: string;
    second: string;
    sec: string;
};
